name: Chip8 - CI

on:
  push:
    branches:
      - main
    paths:
      - 'chip8/**'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: chip8/

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.11'

      - name: Install Requirements
        run:  pip install pytest pytest-cov matplotlib

      - name: Unit Test
        run: |-
          coverage run --source=src/ -m pytest test/
          coverage report -m
          coverage xml -i

