name: Chip8 - CI

on:
  push:
    branches:
      - main
    paths:
      - 'chip8/**'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: chip8/

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Unit Test
        run: |-
          python3 -m pytest -vs test/ --cov=src/ --cov-report=term --cov-report=html

